# Generated by Django 3.1 on 2020-12-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('alternate_number', models.IntegerField()),
                ('email_id', models.CharField(max_length=70)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=70)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
